version: "3"
services:
  app_webapi:
    image: nikitades/whocaresbot-app-webapi
    restart: always
    user: "1000"
    environment:
      APP_ENV: prod
      DATABASE_URL: postgresql://whocaresbot:whocaresbot@database:5432/whocaresbot?serverVersion=13&charset=utf8
      REDIS_DSN: redis://redis:6379
      APP_SECRET: Hk8T66u9ArymEqAmSGzAYB282pCnm0vH
      BOT_TOKEN: 1710037140:AAFydudX1WsxFizF255pVvcjaaJTvCF-eWk
      BOT_NAME: chatanalyticsbot
      CACHE_PERIOD: 300
      PEAK_SEARCH_PERIOD: 720
      MESSENGER_TRANSPORT_DSN: doctrine://default
      LOCK_DSN: flock
    volumes:
      - ./logs/app:/app/var/log:z
    depends_on:
      - app_maintenance
      - database
      - redis
  app_consumer_regular:
    image: nikitades/whocaresbot-app-consumer
    restart: always
    user: "1000"
    deploy:
      replicas: 2
    environment:
      APP_ENV: prod
      DATABASE_URL: postgresql://whocaresbot:whocaresbot@database:5432/whocaresbot?serverVersion=13&charset=utf8
      REDIS_DSN: redis://redis:6379
      APP_SECRET: Hk8T66u9ArymEqAmSGzAYB282pCnm0vH
      BOT_TOKEN: 1710037140:AAFydudX1WsxFizF255pVvcjaaJTvCF-eWk
      BOT_NAME: chatanalyticsbot
      CACHE_PERIOD: 300
      PEAK_SEARCH_PERIOD: 720
      MESSENGER_TRANSPORT_DSN: doctrine://default
      LOCK_DSN: flock
    volumes:
      - ./logs/app:/app/var/log:z
    depends_on:
      - app_maintenance
      - database
      - redis
  app_consumer_slow:
    image: nikitades/whocaresbot-app-consumer-slow
    restart: always
    user: "1000"
    environment:
      APP_ENV: prod
      DATABASE_URL: postgresql://whocaresbot:whocaresbot@database:5432/whocaresbot?serverVersion=13&charset=utf8
      REDIS_DSN: redis://redis:6379
      APP_SECRET: Hk8T66u9ArymEqAmSGzAYB282pCnm0vH
      BOT_TOKEN: 1710037140:AAFydudX1WsxFizF255pVvcjaaJTvCF-eWk
      BOT_NAME: chatanalyticsbot
      CACHE_PERIOD: 300
      PEAK_SEARCH_PERIOD: 720
      MESSENGER_TRANSPORT_DSN: doctrine://default
      LOCK_DSN: flock
    volumes:
      - ./logs/app:/app/var/log:z
    depends_on:
      - app_maintenance
      - database
      - redis
  app_scheduler:
    image: nikitades/whocaresbot-app-scheduler
    restart: always
    user: "1000"
    environment:
      APP_ENV: prod
      DATABASE_URL: postgresql://whocaresbot:whocaresbot@database:5432/whocaresbot?serverVersion=13&charset=utf8
      REDIS_DSN: redis://redis:6379
      APP_SECRET: Hk8T66u9ArymEqAmSGzAYB282pCnm0vH
      BOT_TOKEN: 1710037140:AAFydudX1WsxFizF255pVvcjaaJTvCF-eWk
      BOT_NAME: chatanalyticsbot
      CACHE_PERIOD: 300
      PEAK_SEARCH_PERIOD: 720
      MESSENGER_TRANSPORT_DSN: doctrine://default
      LOCK_DSN: flock
    volumes:
      - ./logs/app:/app/var/log:z
    depends_on:
      - app_maintenance
      - database
      - redis
  app_maintenance:
    image: nikitades/whocaresbot-app-maintenance
    user: "1000"
    restart: "on-failure"
    environment:
      APP_ENV: prod
      DATABASE_URL: postgresql://whocaresbot:whocaresbot@database:5432/whocaresbot?serverVersion=13&charset=utf8
      REDIS_DSN: redis://redis:6379
      APP_SECRET: Hk8T66u9ArymEqAmSGzAYB282pCnm0vH
      BOT_TOKEN: 1710037140:AAFydudX1WsxFizF255pVvcjaaJTvCF-eWk
      BOT_NAME: chatanalyticsbot
      CACHE_PERIOD: 300
      PEAK_SEARCH_PERIOD: 720
      MESSENGER_TRANSPORT_DSN: doctrine://default
      LOCK_DSN: flock
    volumes:
      - ./logs/app:/app/var/log:z
    depends_on:
      - database
      - redis
  nginx:
    image: nikitades/whocaresbot-nginx
    ports:
      - 8087:80
    volumes:
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app_webapi
    restart: always
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: whocaresbot
      POSTGRES_PASSWORD: whocaresbot
    volumes:
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database/files:/var/lib/postgresql/data
    ports:
      - 5434:5432
  redis:
    image: redis:6-alpine
    volumes:
      - ./database/redis:/data
