FROM nikitades/whocaresbot-app-base:arm-latest

USER root

RUN apt update & apt install cron -y

COPY . /app
COPY docker/crontab /etc/cron.d/crontab

WORKDIR /app

RUN chmod 0644 /etc/cron.d/crontab \
    && crontab -u chat-analytics-bot /etc/cron.d/crontab \
    && touch /var/log/cron.log \
    && touch /var/run/crond.pid \
    && chmod 777 /var/run/crond.pid

USER chat-analytics-bot

CMD ["cron", "-f"]