FROM nikitades/whocaresbot-app-base:latest

USER root

RUN mkdir /home/chat-analytics-bot

COPY docker/crontab /etc/cron.d/crontab

RUN chmod 0644 /etc/cron.d/crontab \
    && crontab /etc/cron.d/crontab \
    && touch /var/log/cron.log

CMD ["crond", "-f"]