FROM arm64v8/php:8-cli-alpine

RUN apk add postgresql-dev autoconf gcc g++ make libffi-dev openssl-dev
RUN docker-php-ext-install pdo pdo_pgsql
RUN pecl install -o -f redis &&  rm -rf /tmp/pear &&  docker-php-ext-enable redis

COPY . /app
COPY docker/crontab /etc/cron.d/crontab

WORKDIR /app

RUN chmod 0644 /etc/cron.d/crontab \
    && crontab /etc/cron.d/crontab \
    && touch /var/log/cron.log

CMD ["crond", "-f"]