FROM php:8-fpm-alpine

RUN apk add postgresql-dev
RUN docker-php-ext-install pdo pdo_pgsql

COPY . /app
WORKDIR /app

RUN chmod +x ./docker/entrypoint_migrations.sh

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install

RUN bin/console cache:warmup
RUN composer dump-env prod

ENTRYPOINT ["./docker/entrypoint_migrations.sh"]