FROM arm64v8/php:8-fpm-alpine

RUN apk add postgresql-dev autoconf gcc g++ make libffi-dev openssl-dev shadow
RUN docker-php-ext-install pdo pdo_pgsql pgsql
RUN pecl install -o -f redis &&  rm -rf /tmp/pear &&  docker-php-ext-enable redis

RUN useradd chat-analytics-bot

COPY . /app
WORKDIR /app

RUN chown -R chat-analytics-bot:chat-analytics-bot . && chmod -R 755 .
RUN bin/console cache:warmup

USER chat-analytics-bot